name: Sync LeetCode Solutions

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install LeetCode CLI
        run: |
          pip install leetcode-cli

      - name: Sync LeetCode Solutions
        run: |
          leetcode login --username ${{ secrets.LEETCODE_USERNAME }} --password ${{ secrets.LEETCODE_PASSWORD }}
          leetcode submit --all

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'actions@github.com'
          git add .
          git commit -m "Sync LeetCode solutions"
          git push
